POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldmFodGVjaCIsImlkIjoiNjgwN2VjODVjMTdjYmE5OTdjMmMzZGY3IiwiaWF0IjoxNzQ1NDQwNjIxfQ.TdY59WSaZUNmNOZnur6X-aZN_M-9M8okhfAsywXViIo

{
	"content": "Single page apps use token based auth",
	"important": false
}